version: '3'
services:
  mongodb-service1:
    image: mongo:4.4
    container_name: mongodb-user
    networks:
      - my-network

  mongodb-service2:
    image: mongo:4.4
    container_name: mongodb-post
    networks:
      - my-network

  mongodb-service3:
    image: mongo:4.4
    container_name: mongodb-notification
    networks:
      - my-network

  service1:
    image: node:18
    container_name: user
    depends_on:
      - mongodb-service1
    build:
      context: ./user
    expose:
      - '3000' # Expose the application port
    networks:
      - my-network

  service3:
    image: node:18
    container_name: notification
    depends_on:
      - service1
      - mongodb-service3
    build:
      context: ./notification
    expose:
      - '3000' # Expose the application port
    networks:
      - my-network

  service2:
    image: node:18
    container_name: post
    depends_on:
      - service1
      - service3
      - mongodb-service1
      - mongodb-service3
    build:
      context: ./post
    expose:
      - '3000' # Expose the application port
    networks:
      - my-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/nginx.conf # Update the path to Nginx configuration
    ports:
      - '80:80'
    networks:
      - my-network

networks:
  my-network:
