version: '3'
services:
  mongodb-service1:
    image: mongo:4.4
    container_name: mongodb-user
    volumes:
      - ./data:data/db
    ports:
      - "27017:27017"
    networks:
      - my-network

  mongodb-service2:
    image: mongo:4.4
    container_name: mongodb-post
    volumes:
      - ./data:data/db
    ports:
      - "27017:27017"
    networks:
      - my-network

  mongodb-service3:
    image: mongo:4.4
    container_name: mongodb-notification
    volumes:
      - ./data:data/db
    ports:
      - "27017:27017"
    networks:
      - my-network

  service1:
    container_name: user
    depends_on:
      - mongodb-service1
    build:
      context: ./user
    ports:
      - '3001:3000'
    networks:
      - my-network

  service3:
    container_name: notification
    depends_on:
      - service1
      - mongodb-service3
    build:
      context: ./notification
    ports:
      - '3003:3000'
    networks:
      - my-network

  service2:
    container_name: post
    depends_on:
      - service1
      - service3
      - mongodb-service1
      - mongodb-service3
    build:
      context: ./post
    ports:
      - '3002:3000'
    networks:
      - my-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/nginx.conf
    ports:
      - '80:80'
    networks:
      - my-network

networks:
  my-network:
    external: true
