version: '3'
services:
  service1:
    networks:
      - my-network
    build:
      context: ./user
    ports:
      - '3001:3000'

  service2:
    networks:
      - my-network
    depends_on:
      - service1
      - service3
    build:
      context: ./post
    ports:
      - '3002:3000'

  service3:
    networks:
      - my-network
    depends_on:
      - service1
    build:
      context: ./notification
    ports:
      - '3003:3000'

  mongodb-service1:
    image: mongo
    container_name: mongodb-user
    ports:
      - '27017:27017'

  mongodb-service2:
    image: mongo
    container_name: mongodb-post
    ports:
      - '27018:27017'

  mongodb-service3:
    image: mongo
    container_name: mongodb-notification
    ports:
      - '27019:27017'

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: 'vbZYp0B2DMsmyPGclqDO'
      MINIO_SECRET_KEY: 'IHsSMRuCkig2UKNTRm32TISbKkFYgjajkY4jiW05'
    ports:
      - '9000:9000'
    volumes:
      - ./data:/data  # Map Minio data to a local directory
    command: server /data
