version: '3'
services:
  mongodb-user:
    image: mongo:4.4
    container_name: mongodb-user
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-network

  mongodb-post:
    image: mongo:4.4
    container_name: mongodb-post
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"
    networks:
      - my-network

  mongodb-notification:
    image: mongo:4.4
    container_name: mongodb-notification
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27019:27017"
    networks:
      - my-network

  user:
    container_name: user
    depends_on:
      - mongodb-user
    build:
      context: ./user
    ports:
      - '3001:3000'
    networks:
      - my-network

  notification:
    container_name: notification
    depends_on:
      - user
      - mongodb-notification
    build:
      context: ./notification
    ports:
      - '3003:3000'
    networks:
      - my-network

  post:
    container_name: post
    depends_on:
      - user
      - notification
      - mongodb-user
      - mongodb-notification
    build:
      context: ./post
    ports:
      - '3002:3000'
    networks:
      - my-network

  angular:
    build:
      context: ./front-end
    ports:
      - "4200:4200"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:./nginx.conf
    depends_on:
      - angular
      - notification
      - post
      - user
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    
volumes:
  mongodb_data: