version: '3'
services:
  mongodb-service1:
    image: mongo:4.4
    container_name: mongodb-user
    ports:
      - "27017:27017"
    networks:
      - my-network

  mongodb-service2:
    image: mongo:4.4
    container_name: mongodb-post
    ports:
      - "27018:27017"
    networks:
      - my-network

  mongodb-service3:
    image: mongo:4.4
    container_name: mongodb-notification
    ports:
      - "27019:27017"
    networks:
      - my-network

  service1:
    container_name: user
    depends_on:
      - mongodb-service1
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - my-network

  service3:
    container_name: notification
    depends_on:
      - service1
      - mongodb-service3
    build:
      context: ./notification
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    networks:
      - my-network

  service2:
    container_name: post
    depends_on:
      - service1
      - service3
      - mongodb-service1
      - mongodb-service3
    build:
      context: ./post
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    networks:
      - my-network

  angular-app:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: angular
    container_name: angular
    ports:
      - '4200:80'
    networks:
      - my-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/nginx/nginx.conf
    ports:
      - '80:80'
    networks:
      - my-network
networks:
  my-network:
    external: false
